// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBz2wlU_bnbYDwDuCjb9SXEd8z7R4Qy6zQ',
//     appId: '1:1008762880304:web:e5bd2871619138c4e5c8f5',
//     messagingSenderId: '1008762880304',
//     projectId: 'surveydemo-1ddee',
//     authDomain: 'surveydemo-1ddee.firebaseapp.com',
//     storageBucket: 'surveydemo-1ddee.appspot.com',
//     measurementId: 'G-CEXN8H7BT4',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDe3Yl9LTiLu0Lt9d7efX4ynxcwHtOaDZQ',
//     appId: '1:1008762880304:android:c3c95a43e9987435e5c8f5',
//     messagingSenderId: '1008762880304',
//     projectId: 'surveydemo-1ddee',
//     storageBucket: 'surveydemo-1ddee.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAVNSVWnuJi8MLt034h3BJ16aDsJ5DhCPk',
//     appId: '1:1008762880304:ios:f4328ce6bcf3d3f4e5c8f5',
//     messagingSenderId: '1008762880304',
//     projectId: 'surveydemo-1ddee',
//     storageBucket: 'surveydemo-1ddee.appspot.com',
//     iosBundleId: 'com.example.surveyAppDemo',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAVNSVWnuJi8MLt034h3BJ16aDsJ5DhCPk',
//     appId: '1:1008762880304:ios:f4328ce6bcf3d3f4e5c8f5',
//     messagingSenderId: '1008762880304',
//     projectId: 'surveydemo-1ddee',
//     storageBucket: 'surveydemo-1ddee.appspot.com',
//     iosBundleId: 'com.example.surveyAppDemo',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBz2wlU_bnbYDwDuCjb9SXEd8z7R4Qy6zQ',
//     appId: '1:1008762880304:web:9dbd22f6a5547731e5c8f5',
//     messagingSenderId: '1008762880304',
//     projectId: 'surveydemo-1ddee',
//     authDomain: 'surveydemo-1ddee.firebaseapp.com',
//     storageBucket: 'surveydemo-1ddee.appspot.com',
//     measurementId: 'G-YFZ2H0611Z',
//   );
// }
